-- Generated by Codegen — do not edit by hand
-- Source: http://127.0.0.1:54321
module Supabase.Schema
  ( Orders
  , OrdersRequired
  , OrdersRelations
  , TypeZoo
  , AuditLog
  , AuditLogRequired
  , UserPillars
  , Products
  , ProductsRequired
  , ProductsRelations
  , OptionalEverything
  , OrderItems
  , OrderItemsRequired
  , ProductCategories
  , ProductCategoriesRequired
  , Categories
  , CategoriesRequired
  , CategoriesRelations
  , orders
  , typeZoo
  , auditLog
  , userPillars
  , products
  , optionalEverything
  , orderItems
  , productCategories
  , categories
  , OrderItemsDetailParams
  , orderItemsDetail
  , productCount
  , ProductsCheaperThanParams
  , productsCheaperThan
  , orderSummary
  , internalRealtimeSchema
  , authSchema
  , extensionsSchema
  , graphqlSchema
  , graphqlPublicSchema
  , netSchema
  , pgbouncerSchema
  , publicSchema
  , realtimeSchema
  , storageSchema
  , supabaseFunctionsSchema
  , supabaseMigrationsSchema
  , vaultSchema
  )
  where
import Data.Maybe (Maybe)
import Foreign (Foreign)
import Supabase.Auth.Types (Timestamp)
import Supabase.UUID (UUID)
import Supabase.Types (Rel, Rpc, SchemaName(..), Table, mkRpc, mkTable)
type Orders =
  ( id :: Int
  , product_id :: Int
  , quantity :: Int
  , total_price :: Number
  , status :: String
  , notes :: Maybe String
  , shipped_at :: Maybe Timestamp
  , created_at :: Timestamp
  )

type OrdersRequired =
  (product_id :: Int, total_price :: Number)

type OrdersRelations =
  (order_items :: Rel OrderItems ())

orders :: Table Orders OrdersRequired OrdersRelations
orders = mkTable "orders"

type TypeZoo =
  ( id :: Int
  , col_int2 :: Int
  , col_int4 :: Int
  , col_int8 :: Int
  , col_float4 :: Number
  , col_float8 :: Number
  , col_numeric :: Number
  , col_bool :: Boolean
  , col_text :: String
  , col_varchar :: String
  , col_uuid :: UUID
  , col_timestamptz :: Timestamp
  , col_date :: Timestamp
  , col_jsonb :: Foreign
  , col_json :: Foreign
  , col_text_arr :: Array String
  , col_int_arr :: Array Int
  )

typeZoo :: Table TypeZoo () ()
typeZoo = mkTable "type_zoo"

type AuditLog =
  ( id :: Int
  , table_name :: String
  , record_id :: String
  , action :: String
  , old_data :: Maybe Foreign
  , new_data :: Maybe Foreign
  , created_at :: Timestamp
  )

type AuditLogRequired =
  (table_name :: String, record_id :: String, action :: String)

auditLog :: Table AuditLog AuditLogRequired ()
auditLog = mkTable "audit_log"

type UserPillars =
  ( id :: Int
  , user_id :: UUID
  , pillars :: Array String
  , created_at :: Timestamp
  , updated_at :: Timestamp
  )

userPillars :: Table UserPillars () ()
userPillars = mkTable "user_pillars"

type Products =
  ( id :: Int
  , name :: String
  , description :: Maybe String
  , price :: Number
  , tags :: Array String
  , metadata :: Foreign
  , in_stock :: Boolean
  , created_at :: Timestamp
  , fts :: Maybe String
  )

type ProductsRequired =
  (name :: String)

type ProductsRelations =
  ( orders :: Rel Orders OrdersRelations
  , order_items :: Rel OrderItems ()
  , product_categories :: Rel ProductCategories ()
  )

products :: Table Products ProductsRequired ProductsRelations
products = mkTable "products"

type OptionalEverything =
  ( id :: Int
  , name :: Maybe String
  , count :: Maybe Int
  , amount :: Maybe Number
  , flag :: Maybe Boolean
  , tags :: Maybe (Array String)
  , meta :: Maybe Foreign
  , stamp :: Maybe Timestamp
  )

optionalEverything :: Table OptionalEverything () ()
optionalEverything = mkTable "optional_everything"

type OrderItems =
  ( id :: Int
  , order_id :: Int
  , product_id :: Int
  , quantity :: Int
  , unit_price :: Number
  , discount :: Number
  )

type OrderItemsRequired =
  (order_id :: Int, product_id :: Int, unit_price :: Number)

orderItems :: Table OrderItems OrderItemsRequired ()
orderItems = mkTable "order_items"

type ProductCategories =
  (product_id :: Int, category_id :: UUID)

type ProductCategoriesRequired =
  (product_id :: Int, category_id :: UUID)

productCategories :: Table ProductCategories ProductCategoriesRequired ()
productCategories = mkTable "product_categories"

type Categories =
  ( id :: UUID
  , name :: String
  , parent_id :: Maybe UUID
  , sort_order :: Int
  , created_at :: Timestamp
  )

type CategoriesRequired =
  (name :: String)

type CategoriesRelations =
  (product_categories :: Rel ProductCategories ())

categories :: Table Categories CategoriesRequired CategoriesRelations
categories = mkTable "categories"

type OrderItemsDetailParams =
  (p_order_id :: Int)

orderItemsDetail :: Rpc OrderItemsDetailParams ()
orderItemsDetail = mkRpc "order_items_detail"

productCount :: Rpc () ()
productCount = mkRpc "product_count"

type ProductsCheaperThanParams =
  (max_price :: Number)

productsCheaperThan :: Rpc ProductsCheaperThanParams Products
productsCheaperThan = mkRpc "products_cheaper_than"

orderSummary :: Rpc () ()
orderSummary = mkRpc "order_summary"

internalRealtimeSchema :: SchemaName
internalRealtimeSchema = SchemaName "_realtime"

authSchema :: SchemaName
authSchema = SchemaName "auth"

extensionsSchema :: SchemaName
extensionsSchema = SchemaName "extensions"

graphqlSchema :: SchemaName
graphqlSchema = SchemaName "graphql"

graphqlPublicSchema :: SchemaName
graphqlPublicSchema = SchemaName "graphql_public"

netSchema :: SchemaName
netSchema = SchemaName "net"

pgbouncerSchema :: SchemaName
pgbouncerSchema = SchemaName "pgbouncer"

publicSchema :: SchemaName
publicSchema = SchemaName "public"

realtimeSchema :: SchemaName
realtimeSchema = SchemaName "realtime"

storageSchema :: SchemaName
storageSchema = SchemaName "storage"

supabaseFunctionsSchema :: SchemaName
supabaseFunctionsSchema = SchemaName "supabase_functions"

supabaseMigrationsSchema :: SchemaName
supabaseMigrationsSchema = SchemaName "supabase_migrations"

vaultSchema :: SchemaName
vaultSchema = SchemaName "vault"